FROM golang:alpine

WORKDIR /usr/src/caddy-proxy-organizer

COPY ../ .

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
# COPY go.mod go.sum ./
RUN go mod download && go mod verify

RUN go install

CMD ["/bin/sh"]
#CMD ["caddy-proxy-organizer"] 